// Code generated by goctl. DO NOT EDIT.
package mapper

import (
	"context"
	"github.com/xh-polaris/platform-comment/biz/infrastructure/data/db"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type historyModel interface {
	Insert(ctx context.Context, data *db.History) error
	FindOne(ctx context.Context, id string) (*db.History, error)
	Update(ctx context.Context, data *db.History) error
	Delete(ctx context.Context, id string) error
}

type defaultHistoryModel struct {
	conn *mon.Model
}

func newDefaultHistoryModel(conn *mon.Model) *defaultHistoryModel {
	return &defaultHistoryModel{conn: conn}
}

func (m *defaultHistoryModel) Insert(ctx context.Context, data *db.History) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultHistoryModel) FindOne(ctx context.Context, id string) (*db.History, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data db.History

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHistoryModel) Update(ctx context.Context, data *db.History) error {
	data.UpdateAt = time.Now()

	_, err := m.conn.ReplaceOne(ctx, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultHistoryModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
